/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zayhu_library_jni_Speex */

#ifndef _Included_com_zayhu_library_jni_Speex
#define _Included_com_zayhu_library_jni_Speex
#ifdef __cplusplus
extern "C" {
#endif
#undef com_zayhu_library_jni_Speex_DEFAULT_COMPRESSION
#define com_zayhu_library_jni_Speex_DEFAULT_COMPRESSION 3L
/*
 * Class:     com_zayhu_library_jni_Speex
 * Method:    nativeSpeexOpen
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_Speex_nativeSpeexOpen
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_zayhu_library_jni_Speex
 * Method:    nativeSpeexSetQuality
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_Speex_nativeSpeexSetQuality
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_zayhu_library_jni_Speex
 * Method:    nativeSpeexGetFrameSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_Speex_nativeSpeexGetFrameSize
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_zayhu_library_jni_Speex
 * Method:    nativeSpeexEncode
 * Signature: (I[SI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_Speex_nativeSpeexEncode
  (JNIEnv *, jclass, jint, jshortArray, jint, jbyteArray, jint);

/*
 * Class:     com_zayhu_library_jni_Speex
 * Method:    nativeSpeexDecode
 * Signature: (I[B[SI)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_Speex_nativeSpeexDecode
  (JNIEnv *, jclass, jint, jbyteArray, jshortArray, jint);

/*
 * Class:     com_zayhu_library_jni_Speex
 * Method:    nativeSpeexClose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_zayhu_library_jni_Speex_nativeSpeexClose
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
