/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zayhu_library_jni_Opus */

#ifndef _Included_com_zayhu_library_jni_Opus
#define _Included_com_zayhu_library_jni_Opus
#ifdef __cplusplus
extern "C" {
#endif
#undef com_zayhu_library_jni_Opus_DEFAULT_COMPRESSION
#define com_zayhu_library_jni_Opus_DEFAULT_COMPRESSION 3L
/*
 * Class:     com_zayhu_library_jni_Opus
 * Method:    nativeOpusOpen
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_Opus_nativeOpusOpen
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_zayhu_library_jni_Opus
 * Method:    nativeOpusSetQuality
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_Opus_nativeOpusSetQuality
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_zayhu_library_jni_Opus
 * Method:    nativeOpusSetGain
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_Opus_nativeOpusSetGain
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_zayhu_library_jni_Opus
 * Method:    nativeOpusSetAGC
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_Opus_nativeOpusSetAGC
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_zayhu_library_jni_Opus
 * Method:    nativeOpusGetAGC
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_Opus_nativeOpusGetAGC
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_zayhu_library_jni_Opus
 * Method:    nativeOpusSetDcOffset
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_Opus_nativeOpusSetDcOffset
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_zayhu_library_jni_Opus
 * Method:    nativeOpusGetDcOffset
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_Opus_nativeOpusGetDcOffset
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_zayhu_library_jni_Opus
 * Method:    nativeSetExpectedLossRate
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_Opus_nativeSetExpectedLossRate
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_zayhu_library_jni_Opus
 * Method:    nativeOpusGetFrameSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_Opus_nativeOpusGetFrameSize
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_zayhu_library_jni_Opus
 * Method:    nativeOpusEncode
 * Signature: (I[SI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_Opus_nativeOpusEncode
  (JNIEnv *, jclass, jint, jshortArray, jint, jbyteArray, jint);

/*
 * Class:     com_zayhu_library_jni_Opus
 * Method:    nativeOpusDecode
 * Signature: (I[B[SI)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_Opus_nativeOpusDecode
  (JNIEnv *, jclass, jint, jbyteArray, jshortArray, jint);

/*
 * Class:     com_zayhu_library_jni_Opus
 * Method:    nativeOpusClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_Opus_nativeOpusClose
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
