/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zayhu_library_jni_VoiceCodec */

#ifndef _Included_com_zayhu_library_jni_VoiceCodec
#define _Included_com_zayhu_library_jni_VoiceCodec
#ifdef __cplusplus
extern "C" {
#endif
#undef com_zayhu_library_jni_VoiceCodec_DEFAULT_COMPRESSION
#define com_zayhu_library_jni_VoiceCodec_DEFAULT_COMPRESSION 3L
/*
 * Class:     com_zayhu_library_jni_VoiceCodec
 * Method:    nativeOpen
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_VoiceCodec_nativeOpen
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_zayhu_library_jni_VoiceCodec
 * Method:    nativeClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_VoiceCodec_nativeClose
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_zayhu_library_jni_VoiceCodec
 * Method:    nativeDecode
 * Signature: (I[BII[S)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_VoiceCodec_nativeDecode
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint, jshortArray, jint);

/*
 * Class:     com_zayhu_library_jni_VoiceCodec
 * Method:    nativeEncode
 * Signature: (I[SI[SIS[B)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_VoiceCodec_nativeEncode
  (JNIEnv *, jclass, jint, jshortArray, jint, jshortArray, jint, jshort, jbyteArray);

/*
 * Class:     com_zayhu_library_jni_VoiceCodec
 * Method:    nativeSetCodecState
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_VoiceCodec_nativeSetCodecState
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_zayhu_library_jni_VoiceCodec
 * Method:    nativeGetCodecState
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_VoiceCodec_nativeGetCodecState
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
