/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zayhu_library_jni_OpenSLRecorder */

#ifndef _Included_com_zayhu_library_jni_OpenSLRecorder
#define _Included_com_zayhu_library_jni_OpenSLRecorder
#ifdef __cplusplus
extern "C" {
#endif
#undef com_zayhu_library_jni_OpenSLRecorder_SL_ANDROID_RECORDING_PRESET_NONE
#define com_zayhu_library_jni_OpenSLRecorder_SL_ANDROID_RECORDING_PRESET_NONE 0L
#undef com_zayhu_library_jni_OpenSLRecorder_SL_ANDROID_RECORDING_PRESET_GENERIC
#define com_zayhu_library_jni_OpenSLRecorder_SL_ANDROID_RECORDING_PRESET_GENERIC 1L
#undef com_zayhu_library_jni_OpenSLRecorder_SL_ANDROID_RECORDING_PRESET_CAMCORDER
#define com_zayhu_library_jni_OpenSLRecorder_SL_ANDROID_RECORDING_PRESET_CAMCORDER 2L
#undef com_zayhu_library_jni_OpenSLRecorder_SL_ANDROID_RECORDING_PRESET_VOICE_RECOGNITION
#define com_zayhu_library_jni_OpenSLRecorder_SL_ANDROID_RECORDING_PRESET_VOICE_RECOGNITION 3L
#undef com_zayhu_library_jni_OpenSLRecorder_SL_ANDROID_RECORDING_PRESET_VOICE_COMMUNICATION
#define com_zayhu_library_jni_OpenSLRecorder_SL_ANDROID_RECORDING_PRESET_VOICE_COMMUNICATION 4L
#undef com_zayhu_library_jni_OpenSLRecorder_SL_ANDROID_STREAM_VOICE
#define com_zayhu_library_jni_OpenSLRecorder_SL_ANDROID_STREAM_VOICE 0L
#undef com_zayhu_library_jni_OpenSLRecorder_SL_ANDROID_STREAM_SYSTEM
#define com_zayhu_library_jni_OpenSLRecorder_SL_ANDROID_STREAM_SYSTEM 1L
#undef com_zayhu_library_jni_OpenSLRecorder_SL_ANDROID_STREAM_RING
#define com_zayhu_library_jni_OpenSLRecorder_SL_ANDROID_STREAM_RING 2L
#undef com_zayhu_library_jni_OpenSLRecorder_SL_ANDROID_STREAM_MEDIA
#define com_zayhu_library_jni_OpenSLRecorder_SL_ANDROID_STREAM_MEDIA 3L
#undef com_zayhu_library_jni_OpenSLRecorder_SL_ANDROID_STREAM_ALARM
#define com_zayhu_library_jni_OpenSLRecorder_SL_ANDROID_STREAM_ALARM 4L
#undef com_zayhu_library_jni_OpenSLRecorder_SL_ANDROID_STREAM_NOTIFICATION
#define com_zayhu_library_jni_OpenSLRecorder_SL_ANDROID_STREAM_NOTIFICATION 5L
#undef com_zayhu_library_jni_OpenSLRecorder_CFG_ACTION_MUTE_RECORD
#define com_zayhu_library_jni_OpenSLRecorder_CFG_ACTION_MUTE_RECORD 65537L
#undef com_zayhu_library_jni_OpenSLRecorder_CFG_ACTION_MUTE_PLAY
#define com_zayhu_library_jni_OpenSLRecorder_CFG_ACTION_MUTE_PLAY 65538L
#undef com_zayhu_library_jni_OpenSLRecorder_CFG_ACTION_MUTE_ALL
#define com_zayhu_library_jni_OpenSLRecorder_CFG_ACTION_MUTE_ALL 65539L
#undef com_zayhu_library_jni_OpenSLRecorder_CFG_ACTION_HANDS_FREE
#define com_zayhu_library_jni_OpenSLRecorder_CFG_ACTION_HANDS_FREE 65540L
/*
 * Class:     com_zayhu_library_jni_OpenSLRecorder
 * Method:    nativeCreate
 * Signature: (IIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_OpenSLRecorder_nativeCreate
(JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_zayhu_library_jni_OpenSLRecorder
 * Method:    nativeDestroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_zayhu_library_jni_OpenSLRecorder_nativeDestroy
(JNIEnv *, jclass, jint);

/*
 * Class:     com_zayhu_library_jni_OpenSLRecorder
 * Method:    nativeLastError
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_OpenSLRecorder_nativeLastError
(JNIEnv *, jclass, jint);

/*
 * Class:     com_zayhu_library_jni_OpenSLRecorder
 * Method:    nativePrepareRecording
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_OpenSLRecorder_nativePrepareRecording
(JNIEnv *, jclass, jint);

/*
 * Class:     com_zayhu_library_jni_OpenSLRecorder
 * Method:    nativeStartRecording
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_OpenSLRecorder_nativeStartRecording
(JNIEnv *, jclass, jint);

/*
 * Class:     com_zayhu_library_jni_OpenSLRecorder
 * Method:    nativeStopRecording
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_OpenSLRecorder_nativeStopRecording
(JNIEnv *, jclass, jint);

/*
 * Class:     com_zayhu_library_jni_OpenSLRecorder
 * Method:    nativeSetConfig
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_OpenSLRecorder_nativeSetConfig
(JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_zayhu_library_jni_OpenSLRecorder
 * Method:    nativeGetConfig
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_OpenSLRecorder_nativeGetConfig
(JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_zayhu_library_jni_OpenSLRecorder
 * Method:    nativeRunEncoding
 * Signature: (ILjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_OpenSLRecorder_nativeRunEncoding
(JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_zayhu_library_jni_OpenSLRecorder
 * Method:    nativePlayDataAvailable
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_OpenSLRecorder_nativePlayDataAvailable
(JNIEnv *, jclass, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
