/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zayhu_library_jni_StatisticUtils */

#ifndef _Included_com_zayhu_library_jni_StatisticUtils
#define _Included_com_zayhu_library_jni_StatisticUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zayhu_library_jni_StatisticUtils
 * Method:    nativeFindNthMimimal
 * Signature: ([IIII)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_StatisticUtils_nativeFindNthMinimal
  (JNIEnv *, jclass, jintArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
