/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zayhu_library_jni_WebRTCAECMobile */

#ifndef _Included_com_zayhu_library_jni_WebRTCAECMobile
#define _Included_com_zayhu_library_jni_WebRTCAECMobile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zayhu_library_jni_WebRTCAECMobile
 * Method:    nativeWebRtcAecmInit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_WebRTCAECMobile_nativeWebRtcAecmInit
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_zayhu_library_jni_WebRTCAECMobile
 * Method:    nativeWebRtcAecmBufferFarend
 * Signature: (I[SS)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_WebRTCAECMobile_nativeWebRtcAecmBufferFarend
  (JNIEnv *, jclass, jint, jshortArray, jshort);

/*
 * Class:     com_zayhu_library_jni_WebRTCAECMobile
 * Method:    nativeWebRtcAecmProcess
 * Signature: (I[S[SSS)I
 */
JNIEXPORT jint JNICALL Java_com_zayhu_library_jni_WebRTCAECMobile_nativeWebRtcAecmProcess
  (JNIEnv *, jclass, jint, jshortArray, jshortArray, jshort, jshort);

/*
 * Class:     com_zayhu_library_jni_WebRTCAECMobile
 * Method:    nativeWebRtcAecmFree
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_zayhu_library_jni_WebRTCAECMobile_nativeWebRtcAecmFree
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
